version: '3.8'
services:
  audio-watchdog:
    image: ghcr.io/SilverKnightKMA/audio-watchdog:1.0
    container_name: audio-watchdog
    environment:
      PUID: 1031
      PGID: 65536
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      MUSIC_DIR: /music
      LOG_FILE: /logs/corrupt_files.log
      DB_FILE: /logs/history.db
      RECHECK_DAYS: 30
      LOOP_DELAY: 3600
    volumes:
      - ./logs:/logs
      - ./music:/music
    restart: unless-stopped